# https://leetcode.com/problems/find-the-difference/description/

# 389. Find the Difference

# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter 
# at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.


from collections import Counter as c
def findTheDifference(s, t):
	"""
	:type s: str
	:type t: str
	:rtype: str
	"""
	d1, d2 = c(s), c(t)
	for k in d2.keys():
		if not k in d1:
			return k
		elif d1[k] != d2[k]:
			return k


assert findTheDifference('abcd','abcdz') == 'z'

