# https://leetcode.com/explore/challenge/card/september-leetcoding-challenge/557/week-4-september-22nd-september-28th/3471/


# Find the Difference


# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

# Example:
# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.

########################################################
from collections import Counter
def findTheDifference(s: str, t: str) -> str:
	d1 = Counter(s)
	d2 = Counter(t)
	for key in d1.keys():
		if d2[key] > d1[key]:
			return key
		else:
			d2.pop(key)
	return list(d2.keys())[0]


########################################################
def findTheDifference(s: str, t: str) -> str:
	for c in t:
		if t.count(c) > s.count(c):
			return c

assert(findTheDifference("abcd","abcde") == 'e')
assert(findTheDifference("bb","bbb") == 'b')
assert(findTheDifference("","z") == 'z')






